name: MSRV Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  msrv:
    name: Minimum Supported Rust Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust 1.70.0 (MSRV)
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.70.0

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-msrv-${{ hashFiles('**/Cargo.lock') }}

      - name: Check MSRV
        run: |
          cargo check --all-features
          cargo test --all-features